services:
  main:
    container_name: main
    build:
      context: booking_backend
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - ./booking_backend/.env
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./booking_backend/.env
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  front:
    container_name: front
    build:
      context: booking_front
      dockerfile: Dockerfile
    env_file:
      - ./booking_front/.env
    volumes:
      - /react-app/node_modules
    ports:
      - 3001:3001
    command: npm run start
    depends_on:
      - main
    restart: always
volumes:
  pgdata:
